name: sacriversafety
description: "Sacramento River Safety App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  go_router: ^12.1.3
  get_it: ^7.6.4
  dio: ^5.4.0
  flutter_map: ^8.2.1
  latlong2: ^0.9.0
  fl_chart: ^0.65.0
  intl: ^0.19.0
  logger: ^2.0.2+1
  url_launcher: ^6.2.5
  json_annotation: ^4.9.0
  video_player: ^2.8.1
  youtube_player_flutter: ^8.1.2
  shared_preferences: ^2.2.2
  path_provider: ^2.1.2
  open_file: ^3.3.2
  syncfusion_flutter_pdfviewer: ^24.2.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/data/
    - assets/pdfs/ 